const path = require('path');
require('dotenv').config({ path: path.resolve(__dirname, '.env.local') });

module.exports = {
  apps: [
    {
      name: 'gramii',
      script: 'node_modules/.bin/next',
      args: 'start -p 3000',
      cwd: __dirname,
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '4G',
      env: {
        NODE_ENV: 'production',
        NEXT_PUBLIC_SITE_VARIANT: 'gramii',
        POSTGRES_URL: process.env.POSTGRES_URL_GRAMII,
        JWT_SECRET: process.env.JWT_SECRET,
        REALSITE_API_KEY_GRAMII: process.env.REALSITE_API_KEY_GRAMII,
        REALSITE_API_KEY_ORDA: process.env.REALSITE_API_KEY_ORDA,
        REALSITE_API_URL: process.env.REALSITE_API_URL,
        TWOPM_API_KEY: process.env.TWOPM_API_KEY,
        TWOPM_API_URL: process.env.TWOPM_API_URL,
        INSTAMONSTER_API_KEY_GRAMII: process.env.INSTAMONSTER_API_KEY_GRAMII,
        INSTAMONSTER_API_KEY_ORDA: process.env.INSTAMONSTER_API_KEY_ORDA,
        INSTAMONSTER_API_URL: process.env.INSTAMONSTER_API_URL,
      },
    },
    {
      name: 'orda',
      script: 'node_modules/.bin/next',
      args: 'start -p 3001',
      cwd: __dirname,
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '4G',
      env: {
        NODE_ENV: 'production',
        NEXT_PUBLIC_SITE_VARIANT: 'orda',
        POSTGRES_URL: process.env.POSTGRES_URL_ORDA,
        JWT_SECRET: process.env.JWT_SECRET,
        REALSITE_API_KEY_GRAMII: process.env.REALSITE_API_KEY_GRAMII,
        REALSITE_API_KEY_ORDA: process.env.REALSITE_API_KEY_ORDA,
        REALSITE_API_URL: process.env.REALSITE_API_URL,
        TWOPM_API_KEY: process.env.TWOPM_API_KEY,
        TWOPM_API_URL: process.env.TWOPM_API_URL,
        INSTAMONSTER_API_KEY_GRAMII: process.env.INSTAMONSTER_API_KEY_GRAMII,
        INSTAMONSTER_API_KEY_ORDA: process.env.INSTAMONSTER_API_KEY_ORDA,
        INSTAMONSTER_API_URL: process.env.INSTAMONSTER_API_URL,
      },
    },
  ],
}; 
